#!/usr/bin/env bash
for f in $(find test -name '*.js');
do
	echo "Creating log for ${f}";

	./scripts/instrument "${f}";

	instrumented="${f/.js/_jalangi_.js}";
	./scripts/execute-standalone "${instrumented}";

	dn2=$(dirname "${f}")
	dn1="${dn2/test/}"
	newDirectoryName="${dn1:1}"
	bn=$(basename "${f}")

	newFileName="${bn/.js/.log}"
	mkdir -p "JalangiLogFiles/${newDirectoryName}"

	sort "NEW_LOG_FILE.log" > "JalangiLogFiles/${newDirectoryName}/${newFileName}"
	rm -f "NEW_LOG_FILE.log"
	rm -f "${f/.js/_jalangi_.js}"
	rm -f "${f/.js/_jalangi_.json}"
done