#!/usr/bin/env bash
log_file=$1
test_file=$2

echo "$log_file"

sha="$(sha1sum ${test_file})"
sha="${sha:0:40}"
time="$(date +%s)"
json_rep="{\"sha\":\"${sha}\", \"time\":${time}}"

node --harmony node_modules/jalangi2/src/js/commands/direct.js --analysis src/ValueLogger.js "$log_file" | sort | uniq > "$log_file".log

#Prepend json_rep to log file
echo "${json_rep}" | cat - ${test_file/.js/_jalangi_.js.log} > /tmp/out && mv /tmp/out ${test_file/.js/_jalangi_.js.log}
