#!/bin/bash 
JALANGI_TEST_FILE_FOLDER=$1
TEST_FILE_FOLDER=$2
JALANGI_LOG_FILE_FOLDER=$3

mkdir -p $JALANGI_TEST_FILE_FOLDER
cp -r $TEST_FILE_FOLDER/* $JALANGI_TEST_FILE_FOLDER
./scripts/instrumentHTMLFiles.sh $JALANGI_LOG_FILE_FOLDER
./scripts/startServer.sh
