#!/usr/bin/env bash
file=$1
output=$2
node node_modules/jalangi2/src/js/commands/esnstrument_cli.js --inlineIID --inlineSource "$file"
instrumented="${file/.js/_jalangi_.js}";
mv ${instrumented} ${output} 
