#!/bin/bash

# Usage:
#  <folder> <out-folder>

set -ex

export DBUS_SESSION_BUS_ADDRESS=/dev/null # https://github.com/angular/protractor/issues/2419

cd "$(dirname "$0")"

# going to project root
cd ../../

echo "Starting http server in $1"

ls "$1"

(cd "$1" && nohup http-server -p 8083 >/dev/null 2>&1 &)

sleep 1